Test on minimum, latest, and development versions of dependencies (#21)
* Test on minimum, latest, and development versions of dependencies

I've also changed the version specifiers to be `>=`, except black,
which has intentionally been set to use `~=`, as the formatting can
change between major releases.

Fixes #9.

* Use `pip install tox` in the test workflows

* Simplify and use splitlines appropriately in setup.py

* Save the original requirements file aside so setup.py will work

* Remove tox from `requirements-dev.txt`

* Add explanatory comment about black version specifier

* Install the minimum supported tox version

* Fix requirements installation under tox 2.1

tox 2.1 is the minimum version we claim to support.  Prior to this,
it gave the following error:

    ERROR: Could not open requirements file: [Errno 2] No such file or directory: ' requirements.txt'